apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: certificates-manager
  labels:
    app.kubernetes.io/name: certificates
    app.kubernetes.io/managed-by: kustomize
spec:
  minAvailable: 1
  selector:
    matchLabels:
      control-plane: certificates
      app.kubernetes.io/name: certificates
