apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: certificates
    app.kubernetes.io/managed-by: kustomize
  name: certificates-webhook
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    control-plane: certificates
    app.kubernetes.io/name: certificates
