apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: milo-system

resources:
  - ../../base/crd

components:
  - ../../base/webhook
  - ../../components/iam
  - ../../components/discovery
