apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - target:
      kind: Deployment
      name: certificates-manager
    patch: |-
      - op: remove
        path: /spec/template/spec/containers/0/volumeMounts/1
      - op: remove
        path: /spec/template/spec/volumes/1
  - target:
      kind: Deployment
      name: certificates-manager
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: certificates-manager
      spec:
        template:
          spec:
            containers:
              - name: manager
                volumeMounts:
                  - mountPath: /etc/kubernetes/pki/trust
                    name: trust-bundle
                    readOnly: true
                  - mountPath: /etc/kubernetes/pki/webhook
                    name: webhook-cert
                    readOnly: true
                  - mountPath: /etc/kubernetes/projects/pki/client
                    name: client-cert
                    readOnly: true
                  - mountPath: /etc/kubernetes/project-discovery/auth
                    name: discovery-kubeconfig
                    readOnly: true
                  - mountPath: /etc/kubernetes/projects/auth
                    name: project-kubeconfig-template
                    readOnly: true
            volumes:
              - name: trust-bundle
                configMap:
                  name: datum-control-plane-trust-bundle
              - name: discovery-kubeconfig
                configMap:
                  name: certificates-discovery-kubeconfig
              - name: project-kubeconfig-template
                configMap:
                  name: certificates-project-kubeconfig-template
              - name: webhook-cert
                csi:
                  driver: csi.cert-manager.io
                  readOnly: true
                  volumeAttributes:
                    csi.cert-manager.io/common-name: certificates-webhook
                    csi.cert-manager.io/fs-group: "65532"
                    csi.cert-manager.io/issuer-kind: ClusterIssuer
                    csi.cert-manager.io/issuer-name: datum-control-plane
                    csi.cert-manager.io/dns-names: certificates-webhook.certificates-system.svc,certificates-webhook.certificates-system.svc.cluster.local
              - name: client-cert
                csi:
                  driver: csi.cert-manager.io
                  readOnly: true
                  volumeAttributes:
                    csi.cert-manager.io/common-name: system:control@certificates.miloapis.com
                    csi.cert-manager.io/fs-group: "65532"
                    csi.cert-manager.io/issuer-kind: ClusterIssuer
                    csi.cert-manager.io/issuer-name: datum-control-plane
                    csi.cert-manager.io/key-usages: client auth
                    csi.cert-manager.io/organizations: certificates.miloapis.com
