apiVersion: apps/v1
kind: Deployment
metadata:
  name: certificates-manager
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: manager
        image: ghcr.io/milo-os/certificates:dev
