apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: certificates-system

resources:
  - ../../base/crd
  - ../../base/manager
  - ../../base/certmanager

components:
  - ../../components/namespace
  - ../../base/webhook
  - ../../components/leader_election
  - ../../components/controller_rbac
  - ../../components/prometheus

configMapGenerator:
  - name: certificates-config
    behavior: replace
    files:
      - config.yaml
    options:
      disableNameSuffixHash: true

patches:
  - target:
      kind: Certificate
      name: certificates-serving-cert
    patch: |-
      - op: replace
        path: /spec/dnsNames
        value:
          - certificates-webhook.certificates-system.svc
          - certificates-webhook.certificates-system.svc.cluster.local

replacements:
  - source:
      kind: Certificate
      group: cert-manager.io
      version: v1
      name: certificates-serving-cert
      fieldPath: .metadata.namespace
    targets:
      - select:
          kind: ValidatingWebhookConfiguration
        fieldPaths:
          - .metadata.annotations.[cert-manager.io/inject-ca-from]
        options:
          delimiter: '/'
          index: 0
          create: true
  - source:
      kind: Certificate
      group: cert-manager.io
      version: v1
      name: certificates-serving-cert
      fieldPath: .metadata.name
    targets:
      - select:
          kind: ValidatingWebhookConfiguration
        fieldPaths:
          - .metadata.annotations.[cert-manager.io/inject-ca-from]
        options:
          delimiter: '/'
          index: 1
          create: true
