apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: certificates-system

resources:
  - ../../base/manager

components:
  - ../../components/namespace
  - ../../components/leader_election
  - ../../components/controller_rbac
  - ../../components/milo-integration
  - ../../components/prometheus

configMapGenerator:
  - name: certificates-config
    behavior: replace
    files:
      - config.yaml
    options:
      disableNameSuffixHash: true
